### PR TITLE
fix: added github workspace to safe directory

### PR DESCRIPTION
**Pull request by islerfab**
This fixes the troubles that this github action has related to https://github.com/actions/checkout/issues/766.

I've tested this with my fork, and it solves the issue.

### CODE REVIEW

**Comment by islerfab** [comment]
I added a fix for the source->wiki sync as well, because the temp_dir also has to be whitelisted.

**Comment by gastaldi** [comment]
I confirm this fixes the issue I'm having too. Please merge this ASAP

**Review by jbeveland27 — APPROVED** [review]

**Comment by jbeveland27** [comment]
Thanks for the contribution @islerfab!

**Comment by jbeveland27** [comment]
@islerfab @gastaldi [Release v1.0.1](https://github.com/newrelic/wiki-sync-action/releases/tag/v1.0.1) should contain what you need. While I'm here I updated the default branch to be `main` as well, but also left `master` in tact so as to not break existing workflows. If you have the chance I'd recommend updating your workflows like so:

```
- name: Sync docs to wiki
  uses: newrelic/wiki-sync-action@main
```

**Comment by gastaldi** [comment]
Thank you @jbeveland27! 
Good job with the fix @islerfab !

**Pull request merged**
